### ISSUE TITLE
Increase Decimal Precision

### ISSUE THREAD

**Issue by JSticker** [mirumee/django-prices-openexchangerates#13]
openexchangerates.org is now returning rates with 6 decimal places:
```
  "rates": {
    "AED": 3.673094,
    "AFN": 68.400001,
    "ALL": 123.989001,
```
this causes the 'update_exchange_rates' management command to fail with the following error:
```
django.core.exceptions.ValidationError: {'rate': ['Ensure that there are no more than 5 decimal places.']}
```

Increasing the decimal_places property on the rate field of the ConversionRate model to 6 seems to fix this.

**Comment by artursmet** [comment]
Fixed in 0.1.9
